# Generated by Django 3.2.18 on 2023-06-10 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('name', models.CharField(default='bm', max_length=20)),
                ('updated', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
