# Generated by Django 3.2.19 on 2023-06-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230628_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='status',
            field=models.CharField(default='active', max_length=30),
        ),
    ]
