# Generated by Django 3.2.18 on 2023-05-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230524_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[(1, 'Admin'), (2, 'PRAgency'), (3, 'BrandManager')], max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
