# Generated by Django 3.2.18 on 2023-06-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_invitedusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedusers',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('PRAgency', 'PRAgency'), ('BrandManager', 'BrandManager')], max_length=30, null=True),
        ),
    ]
