# Generated by Django 3.2.19 on 2023-06-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useraccount_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('suspended', 'suspended')], default='active', max_length=30),
        ),
    ]
