# Generated by Django 4.2.2 on 2023-06-16 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=20)),
                ('campaigns_count', models.IntegerField(blank=True, null=True)),
                ('updated', models.DateField(default=django.utils.timezone.now)),
                ('created', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='ChildAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('toddler', 'toddler'), ('preschooler', 'preschooler'), ('elementary', 'elementary'), ('teen', 'teen'), ('adult', 'adult'), ('None', 'None')], max_length=200)),
                ('min_age', models.IntegerField(blank=True, default=0, null=True)),
                ('max_age', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Fashion', 'Fashion'), ('Music', 'Music'), ('Food', 'Food'), ('Health', 'Health'), ('Gaming', 'Gaming'), ('Dance', 'Dance'), ('Entertainment', 'Entertainment'), ('Family', 'Family'), ('Kids', 'Kids'), ('Other', 'Other')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=20)),
                ('updated', models.DateField(default=django.utils.timezone.now)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('total_posts', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('username', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('followers', models.IntegerField(blank=True, default=0, null=True)),
                ('postcost', models.IntegerField(blank=True, default=0, null=True)),
                ('storycost', models.IntegerField(blank=True, default=0, null=True)),
                ('isparent', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20, null=True)),
                ('children_count', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('engagement_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('children_age', models.ManyToManyField(blank=True, default='None', to='base.childage')),
                ('interests', models.ManyToManyField(blank=True, default='Other', to='base.interest')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('campaign_name', models.CharField(default='', max_length=50)),
                ('budget', models.IntegerField(default=0)),
                ('campaign_type', models.CharField(blank=True, choices=[('Periodic', 'Periodic'), ('Single', 'Single'), ('Both', 'Both')], default='Periodic', max_length=20, null=True)),
                ('keyword', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('updated', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('ended', models.DateField(default=django.utils.timezone.now)),
                ('influencers', models.ManyToManyField(blank=True, default='', null=True, to='base.influencer')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
