# Generated by Django 4.2.2 on 2023-06-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(blank=True, choices=[('Periodic', 'Periodic'), ('Single', 'Single'), ('Both', 'Both')], default='Periodic', max_length=20),
        ),
    ]
