# Generated by Django 3.2.19 on 2023-06-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_status',
            field=models.CharField(blank=True, choices=[('Periodic', 'Periodic'), ('Single', 'Single'), ('Both', 'Both')], default='Active', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
