# Generated by Django 3.2.18 on 2023-06-16 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('toddler', 'toddler'), ('preschooler', 'preschooler'), ('elementary', 'elementary'), ('teen', 'teen'), ('adult', 'adult'), ('None', 'None')], max_length=200)),
                ('min_age', models.IntegerField(blank=True, default=0, null=True)),
                ('max_age', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Fashion', 'Fashion'), ('Music', 'Music'), ('Food', 'Food'), ('Health', 'Health'), ('Gaming', 'Gaming'), ('Dance', 'Dance'), ('Entertainment', 'Entertainment'), ('Family', 'Family'), ('Kids', 'Kids'), ('Other', 'Other')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=20)),
                ('updated', models.DateField(default=django.utils.timezone.now)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('total_posts', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='host',
        ),
        migrations.RemoveField(
            model_name='room',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='samplemodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='brandmanager_name',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='campaigns_done',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='description',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='hashtag',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='host',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='name',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='status',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='influencerCampaignCount',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='influencerChildrenAge',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='influencerChildrenCount',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='influencerFollowerCount',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='influencerFollowingCount',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='influencerInfluencerPostCost',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='influencerPostCount',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='influencerStoryCost',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='influencerStoryCount',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='influencer_full_name',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='influencer_username',
        ),
        migrations.AddField(
            model_name='brand',
            name='campaigns_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='ended',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='influencers',
            field=models.ManyToManyField(blank=True, default='', null=True, to='base.Influencer'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='keyword',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='children_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='engagement_rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='followers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='fullname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='isparent',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='postcost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='storycost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='brand',
            name='updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(blank=True, choices=[('Periodic', 'Periodic'), ('Single', 'Single'), ('Both', 'Both')], default='Periodic', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='updated',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='created',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='updated',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.DeleteModel(
            name='BrandManager',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='SampleModel',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AddField(
            model_name='influencer',
            name='children_age',
            field=models.ManyToManyField(blank=True, default='None', to='base.ChildAge'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='interests',
            field=models.ManyToManyField(blank=True, default='Other', to='base.Interest'),
        ),
    ]
