# Generated by Django 3.2.18 on 2023-03-24 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_auto_20230323_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('Periodic', 'Periodic'), ('Single', 'Single')], default='DEFAULT', max_length=10),
        ),
        migrations.AddField(
            model_name='campaign',
            name='content_type',
            field=models.CharField(blank=True, choices=[('Post', 'Post'), ('Story', 'Story'), ('Both', 'Both')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='hashtag',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Completed', 'Completed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
