# Generated by Django 3.2.19 on 2023-06-17 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20230617_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='storycost',
        ),
    ]
