# Generated by Django 3.2.18 on 2023-03-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230324_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influencerUsername', models.CharField(max_length=20, unique=True)),
                ('influencerFullName', models.CharField(max_length=200)),
                ('influencerBio', models.TextField(blank=True, null=True)),
                ('influencerChildrenCount', models.IntegerField(blank=True, null=True)),
                ('influencerCampaignCount', models.IntegerField(blank=True, null=True)),
                ('influencerChildrenAge', models.IntegerField(blank=True, null=True)),
                ('influencerInfluencerPostCost', models.IntegerField(blank=True, null=True)),
                ('influencerStoryCost', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
