# Generated by Django 3.2.19 on 2023-06-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20230617_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='keyword',
        ),
        migrations.AddField(
            model_name='campaign',
            name='keyword',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
