# Generated by Django 3.2.18 on 2023-03-26 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_admin_brand_brandmanager_pragency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='influencer',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='influencer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='influencer',
            name='influencerFollowerCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='influencerFollowingCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='influencerPostCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='influencerStoryCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brandmanager_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.brandmanager'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='campaigns_done',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='brandmanager',
            name='host',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
