# Generated by Django 3.2.18 on 2023-03-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20230326_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='influencer',
            old_name='influencerBio',
            new_name='influencer_bio',
        ),
        migrations.RenameField(
            model_name='influencer',
            old_name='influencerCampaignCount',
            new_name='influencer_campaign_count',
        ),
        migrations.RenameField(
            model_name='influencer',
            old_name='influencerChildrenAge',
            new_name='influencer_children_age',
        ),
        migrations.RenameField(
            model_name='influencer',
            old_name='influencerChildrenCount',
            new_name='influencer_children_count',
        ),
        migrations.RenameField(
            model_name='influencer',
            old_name='influencerFollowerCount',
            new_name='influencer_follower_count',
        ),
        migrations.RenameField(
            model_name='influencer',
            old_name='influencerFollowingCount',
            new_name='influencer_following_count',
        ),
        migrations.RenameField(
            model_name='influencer',
            old_name='influencerFullName',
            new_name='influencer_full_name',
        ),
        migrations.RenameField(
            model_name='influencer',
            old_name='influencerInfluencerPostCost',
            new_name='influencer_post_cost',
        ),
        migrations.RenameField(
            model_name='influencer',
            old_name='influencerPostCount',
            new_name='influencer_post_count',
        ),
        migrations.RenameField(
            model_name='influencer',
            old_name='influencerStoryCost',
            new_name='influencer_story_cost',
        ),
        migrations.RenameField(
            model_name='influencer',
            old_name='influencerStoryCount',
            new_name='influencer_story_count',
        ),
        migrations.RenameField(
            model_name='influencer',
            old_name='influencerUsername',
            new_name='influencer_username',
        ),
        migrations.AddField(
            model_name='influencer',
            name='influencer_interest',
            field=models.CharField(blank=True, choices=[('Fashion', 'Fashion'), ('Gaming', 'Gaming'), ('Food', 'Food'), ('Entertainment', 'Entertainment'), ('Family', 'Family')], max_length=20, null=True),
        ),
    ]
