# Generated by Django 3.2.18 on 2023-03-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20230326_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='influencer_bio',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='influencer_campaign_count',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='influencer_children_age',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='influencer_children_count',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='influencer_follower_count',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='influencer_following_count',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='influencer_interest',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='influencer_post_cost',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='influencer_post_count',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='influencer_story_cost',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='influencer_story_count',
        ),
    ]
