# Generated by Django 3.2.18 on 2023-03-26 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20230326_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Influencer',
        ),
    ]
