# Generated by Django 4.1.7 on 2023-03-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_influencer'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin_username',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='pragency',
            name='pragency_username',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
