# Generated by Django 3.2.18 on 2023-05-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_alter_newinfluencer_isparent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcampaign',
            name='campaign_type',
            field=models.CharField(choices=[('Periodic', 'Periodic'), ('Single', 'Single'), ('Both', 'Both')], default='DEFAULT', max_length=20),
        ),
    ]
