# Generated by Django 3.2.18 on 2023-05-04 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_alter_newcampaign_campaign_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newcampaign',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='pragency',
            old_name='pragency_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='pragency',
            old_name='pragency_username',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='newcampaign',
            name='campaign_type',
        ),
        migrations.AddField(
            model_name='newcampaign',
            name='created',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='newcampaign',
            name='updated',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
