# Generated by Django 3.2.18 on 2023-05-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_auto_20230504_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcampaign',
            name='campaign_type',
            field=models.CharField(choices=[('Periodic', 'Periodic'), ('Single', 'Single'), ('Both', 'Both')], default='DEFAULT', max_length=20),
        ),
    ]
