# Generated by Django 3.2.18 on 2023-05-06 04:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_newcampaign_campaign_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcampaign',
            name='influencers',
        ),
        migrations.RemoveField(
            model_name='newinfluencer',
            name='brandmanager',
        ),
        migrations.DeleteModel(
            name='PRAgency',
        ),
        migrations.RenameField(
            model_name='influencer',
            old_name='influencerChildrenAge',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='influencer',
            old_name='influencerChildrenCount',
            new_name='children_count',
        ),
        migrations.RenameField(
            model_name='influencer',
            old_name='influencerInfluencerPostCost',
            new_name='followers',
        ),
        migrations.RenameField(
            model_name='influencer',
            old_name='influencer_full_name',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='influencer',
            old_name='influencer_username',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='brand_manager',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='hashtag_campaign',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='image',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='name',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='status',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='influencerStoryCost',
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_name',
            field=models.CharField(default='DEFAULT', max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='ended',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='hashtag',
            field=models.CharField(default='DEFAULT', max_length=50),
        ),
        migrations.AddField(
            model_name='influencer',
            name='children_age',
            field=models.CharField(blank=True, choices=[('toddler', 'toddler'), ('preschooler', 'preschooler'), ('elementary', 'elementary'), ('teen', 'teen'), ('adult', 'adult')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='influencer',
            name='interests',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Music', 'Music'), ('Food', 'Food'), ('Health', 'Health'), ('Gaming', 'Gaming'), ('Dance', 'Dance'), ('Entertainment', 'Entertainment'), ('Family', 'Family'), ('Kids', 'Kids')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='influencer',
            name='isparent',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20),
        ),
        migrations.AddField(
            model_name='influencer',
            name='postcost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='influencer',
            name='storycost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('Periodic', 'Periodic'), ('Single', 'Single'), ('Both', 'Both')], default='DEFAULT', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='updated',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='engagement_rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='NewCampaign',
        ),
        migrations.DeleteModel(
            name='NewInfluencer',
        ),
    ]
