# Generated by Django 3.2.18 on 2023-05-06 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_auto_20230506_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='brand_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.brandmanager'),
        ),
    ]
