# Generated by Django 3.2.18 on 2023-05-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_campaign_brand_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
