# Generated by Django 3.2.18 on 2023-05-06 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_campaign_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='hashtag',
            field=models.ForeignKey(default='DEFAULT', on_delete=django.db.models.deletion.CASCADE, to='base.hashtag'),
        ),
    ]
