# Generated by Django 3.2.18 on 2023-05-06 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_alter_campaign_hashtag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='host',
            new_name='brandmanager',
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
