# Generated by Django 3.2.18 on 2023-05-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_auto_20230506_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='content_type',
            field=models.CharField(choices=[('Periodic', 'Periodic'), ('Single', 'Single'), ('Both', 'Both')], default='Post', max_length=20),
        ),
    ]
