# Generated by Django 3.2.18 on 2023-05-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_campaign_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='content_type',
            field=models.CharField(choices=[('Post', 'Post'), ('Story', 'Story'), ('Both', 'Both')], default='Post', max_length=20),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='children_age',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='interests',
            field=models.CharField(default='', max_length=20),
        ),
    ]
