# Generated by Django 3.2.18 on 2023-05-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_auto_20230510_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('toddler', 'toddler'), ('preschooler', 'preschooler'), ('elementary', 'elementary'), ('teen', 'teen'), ('adult', 'adult'), ('None', 'None')], max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='children_age',
        ),
        migrations.AddField(
            model_name='influencer',
            name='children_age',
            field=models.ManyToManyField(default='None', to='base.ChildAge'),
        ),
    ]
