# Generated by Django 3.2.18 on 2023-05-10 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_auto_20230510_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandmanager',
            name='host',
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='subbrand_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.subbrand'),
        ),
        migrations.AlterField(
            model_name='brandmanager',
            name='brandmanager_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('Periodic', 'Periodic'), ('Single', 'Single'), ('Both', 'Both')], default='Periodic', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='hashtag',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='children_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='followers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subbrand',
            name='subbrand_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
