# Generated by Django 3.2.18 on 2023-05-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_auto_20230510_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Post', 'Post'), ('Story', 'Story'), ('Both', 'Both')], max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='influencer',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='content_type',
            field=models.ManyToManyField(default='Post', to='base.ContentType'),
        ),
    ]
