# Generated by Django 3.2.18 on 2023-05-13 04:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_auto_20230511_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='brand_manager',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.brandmanager'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='ended',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='influencers',
            field=models.ManyToManyField(blank=True, default='', null=True, to='base.Influencer'),
        ),
    ]
