# Generated by Django 3.2.18 on 2023-05-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_auto_20230513_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmanager',
            name='brand_name',
            field=models.CharField(default='missing', max_length=20, unique=True),
        ),
    ]
