# Generated by Django 3.2.18 on 2023-05-17 01:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_brandmanager_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmanager',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='brandmanager',
            name='brand_name',
            field=models.CharField(blank=True, default='missing', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='brandmanager',
            name='brandmanager_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='brandmanager',
            name='brandmanager_username',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='brandmanager',
            name='created',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='brandmanager',
            name='updated',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
