# Generated by Django 3.2.18 on 2023-05-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0085_bmlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmlogin',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
