# Generated by Django 3.2.18 on 2023-05-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0086_bmlogin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmlogin',
            name='email',
            field=models.EmailField(default='user', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='bmlogin',
            name='name',
            field=models.CharField(blank=True, default='user', max_length=128, null=True),
        ),
    ]
