# Generated by Django 3.2.18 on 2023-05-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0088_adminlogin_prlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmlogin',
            name='brandName',
            field=models.CharField(blank=True, default='user', max_length=128, null=True),
        ),
    ]
