# Generated by Django 3.2.18 on 2023-05-17 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0089_bmlogin_brandname'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmlogin',
            name='created',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='bmlogin',
            name='brandName',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
