# Generated by Django 3.2.18 on 2023-05-17 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0092_auto_20230517_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmlogin',
            name='created',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='prlogin',
            name='created',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='prlogin',
            name='password',
            field=models.CharField(blank=True, default='pr3', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='prlogin',
            name='updated',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
