# Generated by Django 3.2.18 on 2023-05-17 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0093_auto_20230517_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='user', max_length=128, null=True)),
                ('email', models.EmailField(default='user', max_length=254, unique=True)),
                ('password', models.CharField(blank=True, default='pr3', max_length=128, null=True)),
                ('updated', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('created', models.DateField(blank=True, default=datetime.date.today, null=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='PRRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='user', max_length=128, null=True)),
                ('email', models.EmailField(default='user', max_length=254, unique=True)),
                ('password', models.CharField(blank=True, default='null', max_length=128, null=True)),
                ('confirm_password', models.CharField(blank=True, default='null', max_length=128, null=True)),
                ('updated', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('created', models.DateField(blank=True, default=datetime.date.today, null=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
