# Generated by Django 3.2.18 on 2023-05-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0094_prlist_prregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prlist',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='prlogin',
            name='password',
            field=models.CharField(blank=True, default='null', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='prregistration',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='prregistration',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
