# Generated by Django 3.2.18 on 2023-05-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0095_auto_20230517_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='prlogin',
            name='confirm_password',
            field=models.CharField(blank=True, default='null', max_length=128, null=True),
        ),
    ]
