# Generated by Django 3.2.18 on 2023-05-18 17:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0097_alter_prlogin_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttype',
            name='name',
            field=models.CharField(blank=True, choices=[('Post', 'Post'), ('Story', 'Story'), ('Both', 'Both')], default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='brandmanager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.brandmanager', unique=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='children_age',
            field=models.ManyToManyField(blank=True, default='None', to='base.ChildAge'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='created',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='followers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='fullname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='interests',
            field=models.ManyToManyField(blank=True, default='Other', to='base.Interest'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='isparent',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='postcost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='storycost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='updated',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='CampaignDetailsWithInfluencer',
        ),
    ]
