# Generated by Django 3.2.18 on 2023-05-18 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0098_auto_20230518_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlogin',
            name='email',
            field=models.EmailField(default='user', max_length=254),
        ),
        migrations.AlterField(
            model_name='bmlogin',
            name='email',
            field=models.EmailField(default='user', max_length=254),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='brandmanager',
            name='brand_name',
            field=models.CharField(blank=True, default='missing', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='brandmanager',
            name='brandmanager_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='brandmanager',
            name='brandmanager_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brandmanager',
            name='brandmanager_username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='hashtag',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='brandmanager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.brandmanager'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prlist',
            name='email',
            field=models.EmailField(default='user', max_length=254),
        ),
        migrations.AlterField(
            model_name='prlogin',
            name='email',
            field=models.EmailField(default='user', max_length=254),
        ),
        migrations.AlterField(
            model_name='prregistration',
            name='email',
            field=models.EmailField(default='user', max_length=254),
        ),
        migrations.AlterField(
            model_name='subbrand',
            name='subbrand_name',
            field=models.CharField(max_length=20),
        ),
    ]
