# Generated by Django 3.2.18 on 2023-05-18 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0099_auto_20230518_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminlogin',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='created',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='updated',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
