# Generated by Django 3.2.18 on 2023-05-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0101_auto_20230519_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandmanager',
            name='brand_name',
            field=models.CharField(blank=True, default='missing', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='brandmanager',
            name='brandmanager_name',
            field=models.CharField(blank=True, default='bm', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='brandmanager',
            name='brandmanager_username',
            field=models.CharField(blank=True, default='bm', max_length=20, null=True),
        ),
    ]
