# Generated by Django 3.2.18 on 2023-05-19 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0102_auto_20230519_0437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminlogin',
            options={},
        ),
    ]
