# Generated by Django 3.2.18 on 2023-05-19 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0103_alter_adminlogin_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlogin',
            name='updated',
        ),
    ]
