# Generated by Django 3.2.18 on 2023-05-19 00:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0104_remove_adminlogin_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlogin',
            name='created',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
