# Generated by Django 3.2.18 on 2023-05-22 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0108_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
