# Generated by Django 3.2.18 on 2023-06-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0109_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminLogin',
        ),
        migrations.DeleteModel(
            name='BMLogin',
        ),
        migrations.DeleteModel(
            name='PRList',
        ),
        migrations.DeleteModel(
            name='PRLogin',
        ),
        migrations.DeleteModel(
            name='PRRegistration',
        ),
        migrations.AlterField(
            model_name='brand',
            name='campaigns_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
