# Generated by Django 3.2.18 on 2023-06-09 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0110_auto_20230609_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='ContentType',
        ),
    ]
