# Generated by Django 3.2.18 on 2023-06-16 07:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0111_auto_20230609_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=20)),
                ('updated', models.DateField(default=django.utils.timezone.now)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('total_posts', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='brandmanager',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='hashtag',
            new_name='keyword',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='brandmanager_name',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='subbrand_name',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='brand_manager',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='brandmanager',
        ),
        migrations.DeleteModel(
            name='BrandManager',
        ),
        migrations.DeleteModel(
            name='Hashtag',
        ),
        migrations.DeleteModel(
            name='SubBrand',
        ),
        migrations.AddField(
            model_name='keyword',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.brand'),
        ),
    ]
