# Generated by Django 3.2.18 on 2023-06-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0112_auto_20230616_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='brand',
        ),
        migrations.AddField(
            model_name='childage',
            name='max_age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='childage',
            name='min_age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
